# to install - https://pre-commit.com/#install
# run once: `pre-commit install`
# to run all: `pre-commit run --all-files`
# to update repo: `pre-commit autoupdate`
# it will run on each commit message

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-xml
    -   id: check-toml
    -   id: check-case-conflict
#    -   id: check-shebang-scripts-are-executable
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-symlinks
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: requirements-txt-fixer
    -   id: debug-statements
#-   repo: local
#    hooks:
#    -   id: unittest
#        name: unittest
#        entry: python -m unittest discover .
#        language: system # changing this to python breaks things as per: https://stackoverflow.com/questions/59714740/pre-commit-run-unittest-git-hooks-modulenotfounderror-for-installed-python-modu
#        'types': [ python ]
#        args: [ "-p '*test.py'" ] # Probably this option is absolutely not needed.
#        pass_filenames: false
#        stages: [ commit ]
#-   repo: https://github.com/psf/black
#    rev: 21.7b0
#    hooks:
#    -   id: black
-   repo: https://github.com/regebro/pyroma
    rev: "3.2"
    hooks:
    -   id: pyroma
#-   repo: https://github.com/pre-commit/mirrors-yapf
#    rev: v0.31.0
#    hooks:
#    -   id: yapf
#        additional_dependencies: [toml]
